language: CSharp
mono:
 - latest
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq nodejs git sqlite3 libsqlite3-dev libunwind8 libssl-dev
 - npm install -g bower
 - npm install -g gulp
 - nuget sources Add -Name ASPNETVNEXT -Source https://www.myget.org/F/aspnetvnext/api/v3/index.json
 - nuget sources Add -Name AspNetCi -Source https://www.myget.org/F/aspnetcidev/api/v3/index.json
 - CD SimpleIdentityServer
 - dnu restore