language: CSharp
branches:  
  only:
    - master
mono:
 - latest
addons:
 apt:
  sources:
   - debian-sid
  packages:
   - libunwind8
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq nodejs git sqlite3 libsqlite3-dev libssl-dev
 - npm install -g bower
 - npm install -g gulp
 - nuget sources Add -Name ASPNETVNEXT -Source https://www.myget.org/F/aspnetvnext/api/v3/index.json
 - nuget sources Add -Name AspNetCi -Source https://www.myget.org/F/aspnetcidev/api/v3/index.json
install:
 - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
 - dnvm install 1.0.0-rc1-update1 -alias default -r coreclr
 - dnvm use 1.0.0-rc1-update1 -r coreclr
 - dnu restore SimpleIdentityServer
script:
 - dnu build --framework dnxcore50 ./SimpleIdentityServer/src/SimpleIdentityServer.Core.Common
 - dnu build --framework dnxcore50 ./SimpleIdentityServer/src/SimpleIdentityServer.Logging
 - dnu build --framework dnxcore50 ./SimpleIdentityServer/src/System.Security.Cryptography.Algorithms.Extensions
 - dnu build --framework dnxcore50 ./SimpleIdentityServer/src/SimpleIdentityServer.Core.Jwt
 - dnu build --framework dnxcore50 ./SimpleIdentityServer/src/SimpleIdentityServer.Core
 - dnu restore ./SimpleIdentityServer/tests/SimpleIdentityServer.Core.Jwt.UnitTests
 - dnu restore ./SimpleIdentityServer/tests/SimpleIdentityServer.Core.UnitTests
 - dnx -p ./SimpleIdentityServer/tests/SimpleIdentityServer.Core.Jwt.UnitTests test
 - dnx -p ./SimpleIdentityServer/tests/SimpleIdentityServer.Core.UnitTests test
 - dnx -p ./SimpleIdentityServer/tests/SimpleIdentityServer.Manager.Core.Tests test
