language: CSharp
branches:  
  only:
    - master
mono:
 - latest
before_install:
 - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=1.0.0-rc1-update1 && source ~/.dnx/dnvm/dnvm.sh
 - dnvm install 1.0.0-rc1-update1 -alias default -r coreclr
 - dnvm use 1.0.0-rc1-update1 -r coreclr
 - sudo apt-get update -qq
 - sudo apt-get install -qq nodejs git sqlite3 libsqlite3-dev libunwind8 libssl-dev
 - npm install -g bower
 - npm install -g gulp
 - nuget sources Add -Name ASPNETVNEXT -Source https://www.myget.org/F/aspnetvnext/api/v3/index.json
 - nuget sources Add -Name AspNetCi -Source https://www.myget.org/F/aspnetcidev/api/v3/index.json
 - dnu restore SimpleIdentityServer