version: 1.0.{build}
skip_non_tags: true
build_script:
- cmd: cd SimpleIdentityServer\src && generate-nugetpkgs.cmd
artifacts:
- path: SimpleIdentityServer\src\feed\*.nupkg
  name: NugetPackages
- path: LokitCa.cer
  name: Certificate