version: 1.0.{build}
configuration: Release
platform: Any CPU
environment:
  matrix:
  - solution_name: SimpleIdentityServer.sln
build_script:
- msbuild %solution_name%
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
- cd SimpleIdentityServer
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
- appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
- nuget-restore
artifacts:
- path: SimpleIdentityServer\bin
  name: SimpleIdentityServer