version: 1.0.{build}
skip_non_tags: true
build_script:
- cmd: cd SimpleIdentityServer\src && dotnet restore && generate-nugetpkgs.cmd
artifacts:
- path: SimpleIdentityServer\src\feed\*.nupkg
  name: NugetPackages
- path: LokitCa.cer
  name: Certificate
- path: SimpleIdentityServer\src\feed
  name: Feed
- path: exports
  name: Exports
deploy:
- provider: NuGet
  api_key:
    secure: pziM2WPIuSTwZLLV+APtqvUB5JqK0bpFIW/DfuYBmD7YjyKoO21px5aHY/qMTQef
  artifact: NugetPackages
  on:
    branch: master
    appveyor_repo_tag: true
- provider: GitHub
  description: SimpleIdentityServer
  auth_token:
    secure: lQ8ijoj6dfshLfFWRKFUrphgt4LkIz1YduZU+S6xuF33ewz1WcySLNJURJysTF11
  artifact: Certificate,Feed,Exports
  on:
    branch: master
    appveyor_repo_tag: true