version: 1.0.{build}
configuration: Debug
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: jYQ6AvQ7svKGDbPHlbsmLaAiL6HPXTIm7YMH7bTGsC+gSTZM9R+Qu+4wAX/4MBfa
install:
- cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe
- cmd: nuget sources Add -Name AspNetVnext -Source https://www.myget.org/F/aspnetvnext/api/v3/index.json
- cmd: npm install bower -g
- cmd: npm install gulp -g
before_build:
- cd SimpleIdentityServer
- cmd: dnvm upgrade
- cmd: dnu restore
build_script:
- cmd: dnu build src\SimpleIdentityServer.Host
- cmd: dnu build src\SimpleIdentityServer.Core
- cmd: dnu build tests\SimpleIdentityServer.Api.Tests
- cmd: dnu build tests\SimpleIdentityServer.Core.Jwt.UnitTests
- cmd: dnu build tests\SimpleIdentityServer.Core.UnitTests
test_script:
#- cmd: dnx -p tests\SimpleIdentityServer.Api.Tests test
- cmd: dnx -p tests\SimpleIdentityServer.Core.Jwt.UnitTests test
- cmd: dnx -p tests\SimpleIdentityServer.Core.UnitTests test
#- cmd: dnx -p tests\SimpleIdentityServer.Oauth2Instrospection.Authentication.Tests test
- cmd: dnx -p tests\SimpleIdentityServer.Manager.Core.Tests test
after_test:
- cmd: '%USERPROFILE%\.dnx\packages\OpenCover\4.6.166\tools\OpenCover.Console.exe -target:"%USERPROFILE%\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-final\bin\dnx.exe" -targetargs:"--lib %APPVEYOR_BUILD_FOLDER%\SimpleIdentityServer\src\SimpleIdentityServer.Core\bin\Debug\dnx451 -p tests\SimpleIdentityServer.Core.UnitTests test" -output:coverage.xml -register:user -filter:+[SimpleIdentityServer.Core]*'
- cmd: '%USERPROFILE%\.dnx\packages\coveralls.io\1.3.4\tools\coveralls.net.exe --opencover coverage.xml'
- cmd: dnu publish src\SimpleIdentityServer.Host -o output\
artifacts:
- path: output
  name: SimpleIdentityServer
deploy:
- provider: GitHub
  description: Simple identity server
  auth_token:
    secure: lQ8ijoj6dfshLfFWRKFUrphgt4LkIz1YduZU+S6xuF33ewz1WcySLNJURJysTF11
  artifact: SimpleIdentityServer
  on:
    branch: master
    appveyor_repo_tag: true