version: 1.0.{build}
skip_non_tags: true
build_script:
- ps: .\Build.ps1
artifacts:
- path: SimpleIdentityServer\src\feed\*.nupkg
  name: NugetPackages
deploy:
- provider: NuGet
  api_key:
    secure: pziM2WPIuSTwZLLV+APtqvUB5JqK0bpFIW/DfuYBmD7YjyKoO21px5aHY/qMTQef
  artifact: NugetPackages
  on:
    branch: master
    appveyor_repo_tag: true