version: 1.0.{build}
configuration: Debug
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: jYQ6AvQ7svKGDbPHlbsmLaAiL6HPXTIm7YMH7bTGsC+gSTZM9R+Qu+4wAX/4MBfa
install:
- cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe
- cmd: nuget sources Add -Name AspNetVnext -Source https://www.myget.org/F/aspnetvnext/api/v3/index.json
- cmd: nuget sources Add -Name AspNetCi -Source https://www.myget.org/F/aspnetcidev/api/v3/index.json
- cmd: npm install bower -g
- cmd: npm install gulp -g
before_build:
- cd SimpleIdentityServer
- cmd: dnvm install 1.0.0-rc1-update1 -r coreclr
- cmd: dnu restore
build_script:
- cmd: dnu build src\SimpleIdentityServer.Host --framework dnxcore50
- cmd: dnu build src\SimpleIdentityServer.Core --framework dnxcore50
#- cmd: dnu build tests\SimpleIdentityServer.Api.Tests --framework dnxcore50
- cmd: dnu build tests\SimpleIdentityServer.Core.Jwt.UnitTests --framework dnxcore50
- cmd: dnu build tests\SimpleIdentityServer.Core.UnitTests --framework dnxcore50
test_script:
#- cmd: dnx -p tests\SimpleIdentityServer.Api.Tests test
- cmd: dnx -p tests\SimpleIdentityServer.Core.Jwt.UnitTests test
- cmd: dnx -p tests\SimpleIdentityServer.Core.UnitTests test
#- cmd: dnx -p tests\SimpleIdentityServer.UserInformation.Authentication.Tests test
#- cmd: dnx -p tests\SimpleIdentityServer.Oauth2Instrospection.Authentication.Tests test
#- cmd: dnx -p tests\SimpleIdentityServer.Manager.Core.Tests test
artifacts:
- path: output
  name: SimpleIdentityServer