version: 1.0.{build}
configuration: Debug
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: jYQ6AvQ7svKGDbPHlbsmLaAiL6HPXTIm7YMH7bTGsC+gSTZM9R+Qu+4wAX/4MBfa
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
- cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
before_build:
- cd SimpleIdentityServer\VNEXT
- cmd: dnvm upgrade
- cmd: dnu restore
build_script:
- cmd: dnu build src\SimpleIdentityServer.Host
- cmd: dnu build tests\SimpleIdentityServer.Api.Tests
- cmd: dnu build tests\SimpleIdentityServer.Core.Jwt.UnitTests
- cmd: dnu build tests\SimpleIdentityServer.Core.UnitTests
# - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe
# - cmd: nuget restore
# - cmd: dnvm upgrade
# - cmd: dnu restore
test_script:
- cmd: dnx -p tests\SimpleIdentityServer.Api.Tests test
- cmd: dnx -p tests\SimpleIdentityServer.Core.Jwt.UnitTests test
- cmd: dnx -p tests\SimpleIdentityServer.Core.UnitTests test
#after_test:
#- packages\OpenCover\4.6.166\tools\OpenCover.Console.exe -register:user -target:"packages\NUnit.Console.3.0.1\tools\nunit3-console.exe" -targetargs:"SimpleIdentityServer.Core.UnitTests\bin\Debug\SimpleIdentityServer.Core.UnitTests.dll" -output:coverage.xml -filter:+[SimpleIdentityServer.Core]*
#- packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

#artifacts:
#- path: SimpleIdentityServer\SimpleIdentityServer\bin
#  name: SimpleIdentityServer
#deploy:
#- provider: GitHub
#  description: Simple identity server
#  auth_token:
#    secure: lQ8ijoj6dfshLfFWRKFUrphgt4LkIz1YduZU+S6xuF33ewz1WcySLNJURJysTF11
#  artifact: SimpleIdentityServer
#  on:
#    branch: master
#    appveyor_repo_tag: true