version: 1.0.{build}
configuration: Debug
platform: Any CPU
environment:
  matrix:
  - solution_name: SimpleIdentityServer.sln
  COVERALLS_REPO_TOKEN:
    secure: jYQ6AvQ7svKGDbPHlbsmLaAiL6HPXTIm7YMH7bTGsC+gSTZM9R+Qu+4wAX/4MBfa
build_script:
- msbuild %solution_name%
install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
before_build:
- cd SimpleIdentityServer
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
- appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
- cmd: References\dnx-clr-win-x86.1.0.0-rc1-update1\dnu.cmd restore
- nuget-restore
after_test:
- packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"packages\NUnit.Console.3.0.1\tools\nunit3-console.exe" -targetargs:"SimpleIdentityServer.Core.UnitTests\bin\Debug\SimpleIdentityServer.Core.UnitTests.dll" -output:coverage.xml -filter:+[SimpleIdentityServer.Core]*
- packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
artifacts:
- path: SimpleIdentityServer\SimpleIdentityServer\bin
  name: SimpleIdentityServer
deploy:
- provider: GitHub
  description: Simple identity server
  auth_token:
    secure: lQ8ijoj6dfshLfFWRKFUrphgt4LkIz1YduZU+S6xuF33ewz1WcySLNJURJysTF11
  artifact: SimpleIdentityServer
  on:
    branch: master
    appveyor_repo_tag: true