version: '2'
services:
 web:
  build:
   dockerfile: Dockerfile-Authorization
   context: .
  ports:
   - "5000:5000"
  links:
   - postgresql
  depends_on:
   - "postgresql"
  environment:
   - DB_ALIAS=postgresql
   - DB_PORT=5432
 postgresql:
  image: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=postgres