version: '2'
services:
 web:
  build:
   dockerfile: Dockerfile-Authorization
   context: .
  ports:
   - "5000:5000"
  depends_on:
   - postgresql
  links:
   - postgresql
 postgresql:
  image: postgres
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=password
   - POSTGRES_DB=postgres